<?php
declare(strict_types=1);
require __DIR__ . '/bootstrap.php';
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store');
function respond(mixed $data=null, ?array $error=null, int $status=200): never { http_response_code($status); echo json_encode(['ok'=>$error===null,'data'=>$data,'error'=>$error], JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES); exit; }
function fail(string $code,string $message,int $status=400): never { respond(null,['code'=>$code,'message'=>$message],$status); }
function input(): array { $body=json_decode(file_get_contents('php://input'),true); return is_array($body)?$body:$_POST; }
function bearer(): string { return preg_replace('/^Bearer\\s+/i','',$_SERVER['HTTP_AUTHORIZATION']??'')?:''; }
function current_user(): ?array { $token=bearer(); if(!$token)return null; $q=db()->prepare('SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>NOW() AND u.active=1');$q->execute([hash('sha256',$token)]);return $q->fetch()?:null; }
function auth(): array { $u=current_user();if(!$u)fail('AUTH_REQUIRED','Требуется авторизация.',401);return $u; }
function admin(): array { $u=auth();if(!in_array($u['role'],['admin','staff'],true))fail('FORBIDDEN','Недостаточно прав.',403);return $u; }
function slot(int $masterId,int $serviceId,string $startsAt,bool $lock=false): array { $q=db()->prepare('SELECT s.*,m.name master_name FROM services s JOIN master_services ms ON ms.service_id=s.id JOIN masters m ON m.id=ms.master_id WHERE s.id=? AND m.id=? AND s.active=1 AND m.active=1');$q->execute([$serviceId,$masterId]);$service=$q->fetch();if(!$service)fail('NOT_AVAILABLE','Услуга или мастер недоступны.');$start=DateTimeImmutable::createFromFormat('Y-m-d H:i:s',$startsAt);if(!$start||$start->format('Y-m-d H:i:s')!==$startsAt)fail('INVALID_DATETIME','Некорректные дата и время.');$end=$start->modify('+'.(int)$service['duration_min'].' minutes');if($start<=new DateTimeImmutable())fail('PAST_DATETIME','Нельзя выбрать прошедшее время.');$q=db()->prepare('SELECT id FROM days_off WHERE master_id=? AND day=?');$q->execute([$masterId,$start->format('Y-m-d')]);if($q->fetch())fail('DAY_OFF','В этот день мастер не работает.');$q=db()->prepare('SELECT starts,ends FROM working_hours WHERE master_id=? AND weekday=?');$q->execute([$masterId,(int)$start->format('N')]);$hours=$q->fetch();if(!$hours||$start->format('H:i:s')<$hours['starts']||$end->format('H:i:s')>$hours['ends'])fail('OUTSIDE_HOURS','Время вне рабочего графика.');$sql="SELECT id FROM bookings WHERE master_id=? AND status IN ('pending','confirmed') AND starts_at<? AND ends_at>?".($lock?' FOR UPDATE':'');$q=db()->prepare($sql);$q->execute([$masterId,$end->format('Y-m-d H:i:s'),$start->format('Y-m-d H:i:s')]);if($q->fetch())fail('SLOT_TAKEN','Это время уже занято.');return [$service,$start,$end];}
function public_user(array $u): array { unset($u['password_hash']);return $u; }
$action=(string)($_GET['action']??'');
try { switch($action) {
case 'health': respond(['database'=>(bool)db()->query('SELECT 1')->fetchColumn()]);
case 'services': respond(db()->query('SELECT id,name,description,price,duration_min FROM services WHERE active=1 ORDER BY id')->fetchAll());
case 'masters': $id=(int)($_GET['service_id']??0);$q=db()->prepare('SELECT DISTINCT m.id,m.name,m.specialty,m.bio FROM masters m JOIN master_services ms ON ms.master_id=m.id WHERE m.active=1 AND (?=0 OR ms.service_id=?) ORDER BY m.id');$q->execute([$id,$id]);respond($q->fetchAll());
case 'availability': $master=(int)($_GET['master_id']??0);$service=(int)($_GET['service_id']??0);$date=(string)($_GET['date']??'');$day=DateTimeImmutable::createFromFormat('!Y-m-d',$date);if(!$day)fail('INVALID_DATE','Некорректная дата.');$q=db()->prepare('SELECT starts,ends FROM working_hours WHERE master_id=? AND weekday=?');$q->execute([$master,(int)$day->format('N')]);$hours=$q->fetch();if(!$hours)respond([]);$q=db()->prepare('SELECT duration_min FROM services WHERE id=? AND active=1');$q->execute([$service]);$duration=(int)$q->fetchColumn();if(!$duration)fail('NOT_AVAILABLE','Услуга недоступна.');$q=db()->prepare("SELECT starts_at,ends_at FROM bookings WHERE master_id=? AND DATE(starts_at)=? AND status IN ('pending','confirmed')");$q->execute([$master,$date]);$busy=$q->fetchAll();$slots=[];$cursor=new DateTimeImmutable($date.' '.$hours['starts']);$close=new DateTimeImmutable($date.' '.$hours['ends']);while($cursor->modify('+'.$duration.' minutes')<=$close){$end=$cursor->modify('+'.$duration.' minutes');$free=true;foreach($busy as $b){if($cursor->format('Y-m-d H:i:s')<$b['ends_at']&&$end->format('Y-m-d H:i:s')>$b['starts_at']){$free=false;break;}}if($free&&$cursor>new DateTimeImmutable())$slots[]=$cursor->format('Y-m-d H:i:s');$cursor=$cursor->modify('+30 minutes');}respond($slots);
case 'register': $i=input();$email=strtolower(trim((string)($i['email']??'')));$password=(string)($i['password']??'');$first=trim((string)($i['first_name']??''));$last=trim((string)($i['last_name']??''));if(!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($password)<8||!$first||!$last)fail('INVALID_INPUT','Проверьте имя, email и пароль (минимум 8 символов).');$q=db()->prepare('INSERT INTO users(email,password_hash,first_name,last_name) VALUES(?,?,?,?)');try{$q->execute([$email,password_hash($password,PASSWORD_DEFAULT),$first,$last]);}catch(PDOException $e){if($e->errorInfo[1]===1062)fail('EMAIL_EXISTS','Пользователь уже зарегистрирован.');throw $e;} $user=db()->query('SELECT * FROM users WHERE id='.db()->lastInsertId())->fetch();$token=bin2hex(random_bytes(32));$q=db()->prepare('INSERT INTO sessions(user_id,token_hash,expires_at) VALUES(?,?,DATE_ADD(NOW(),INTERVAL 30 DAY))');$q->execute([$user['id'],hash('sha256',$token)]);respond(['token'=>$token,'user'=>public_user($user)]);
case 'login': $i=input();$q=db()->prepare('SELECT * FROM users WHERE email=? AND active=1');$q->execute([strtolower(trim((string)($i['email']??'')))]);$user=$q->fetch();if(!$user||!password_verify((string)($i['password']??''),$user['password_hash']))fail('INVALID_LOGIN','Неверный email или пароль.',401);$token=bin2hex(random_bytes(32));$q=db()->prepare('INSERT INTO sessions(user_id,token_hash,expires_at) VALUES(?,?,DATE_ADD(NOW(),INTERVAL 30 DAY))');$q->execute([$user['id'],hash('sha256',$token)]);respond(['token'=>$token,'user'=>public_user($user)]);
case 'logout': if(bearer()){ $q=db()->prepare('DELETE FROM sessions WHERE token_hash=?');$q->execute([hash('sha256',bearer())]); }respond(['logged_out'=>true]);
case 'me': respond(public_user(auth()));
case 'booking.create': $u=auth();$i=input();$pdo=db();$pdo->beginTransaction();try{[$service,$start,$end]=slot((int)($i['master_id']??0),(int)($i['service_id']??0),(string)($i['starts_at']??''),true);$q=$pdo->prepare('INSERT INTO bookings(user_id,master_id,service_id,starts_at,ends_at,note) VALUES(?,?,?,?,?,?)');$q->execute([$u['id'],$i['master_id'],$i['service_id'],$start->format('Y-m-d H:i:s'),$end->format('Y-m-d H:i:s'),trim((string)($i['note']??''))]);$id=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO booking_events(booking_id,event_type,payload) VALUES(?,?,?)')->execute([$id,'booking.created',json_encode(['booking_id'=>$id],JSON_THROW_ON_ERROR)]);$pdo->commit();respond(['id'=>$id,'starts_at'=>$start->format('Y-m-d H:i:s'),'ends_at'=>$end->format('Y-m-d H:i:s')],null,201);}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
case 'bookings.mine': $u=auth();$q=db()->prepare('SELECT b.*,s.name service_name,m.name master_name FROM bookings b JOIN services s ON s.id=b.service_id JOIN masters m ON m.id=b.master_id WHERE b.user_id=? ORDER BY b.starts_at DESC');$q->execute([$u['id']]);respond($q->fetchAll());
case 'booking.cancel': $u=auth();$q=db()->prepare("UPDATE bookings SET status='cancelled' WHERE id=? AND user_id=? AND status IN ('pending','confirmed')");$q->execute([(int)(input()['booking_id']??0),$u['id']]);respond(['cancelled'=>$q->rowCount()===1]);
case 'admin.bookings': admin();respond(db()->query('SELECT b.*,u.email,u.first_name,u.last_name,s.name service_name,m.name master_name FROM bookings b JOIN users u ON u.id=b.user_id JOIN services s ON s.id=b.service_id JOIN masters m ON m.id=b.master_id ORDER BY b.starts_at DESC')->fetchAll());
case 'admin.booking.status': admin();$i=input();$status=(string)($i['status']??'');if(!in_array($status,['pending','confirmed','completed','cancelled'],true))fail('INVALID_STATUS','Некорректный статус.');$q=db()->prepare('UPDATE bookings SET status=? WHERE id=?');$q->execute([$status,(int)($i['booking_id']??0)]);respond(['updated'=>$q->rowCount()===1]);
default: fail('NOT_FOUND','Маршрут не найден.',404); } } catch(PDOException $e){error_log($e->getMessage());fail('SERVER_ERROR','Внутренняя ошибка сервера.',500);} catch(Throwable $e){if($e instanceof RuntimeException)fail('REQUEST_ERROR',$e->getMessage());error_log($e->getMessage());fail('SERVER_ERROR','Внутренняя ошибка сервера.',500);}
